// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// EMcppARMSI
SEXP EMcppARMSI(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSI(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSI(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIA
SEXP EMcppARMSIA(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSIA(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIA(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIAH
SEXP EMcppARMSIAH(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSIAH(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIAH(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIH
SEXP EMcppARMSIH(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSIH(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIH(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIHPenalized
SEXP EMcppARMSIHPenalized(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min, Rcpp::NumericVector sigma_null_rcpp, double penalty_term);
RcppExport SEXP _rMSWITCH_EMcppARMSIHPenalized(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP, SEXP sigma_null_rcppSEXP, SEXP penalty_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_null_rcpp(sigma_null_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_term(penalty_termSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIHPenalized(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, sigma_null_rcpp, penalty_term));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIHQuZhuo
SEXP EMcppARMSIHQuZhuo(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSIHQuZhuo(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIHQuZhuo(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSIQuZhuo
SEXP EMcppARMSIQuZhuo(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min);
RcppExport SEXP _rMSWITCH_EMcppARMSIQuZhuo(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSIQuZhuo(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSM
SEXP EMcppARMSM(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_EMcppARMSM(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSM(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSMAH
SEXP EMcppARMSMAH(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_EMcppARMSMAH(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSMAH(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// EMcppARMSMH
SEXP EMcppARMSMH(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix beta0_rcpp, Rcpp::NumericVector mu0_rcpp, Rcpp::NumericVector sigma0_rcpp, Rcpp::NumericMatrix gamma_dependent0_rcpp, Rcpp::NumericMatrix gamma_independent0_rcpp, Rcpp::NumericMatrix transition_probs0_rcpp, Rcpp::NumericVector initial_dist0_rcpp, int maxit, double epsilon, double transition_probs_min, double transition_probs_max, double sigma_min, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_EMcppARMSMH(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP beta0_rcppSEXP, SEXP mu0_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP gamma_dependent0_rcppSEXP, SEXP gamma_independent0_rcppSEXP, SEXP transition_probs0_rcppSEXP, SEXP initial_dist0_rcppSEXP, SEXP maxitSEXP, SEXP epsilonSEXP, SEXP transition_probs_minSEXP, SEXP transition_probs_maxSEXP, SEXP sigma_minSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta0_rcpp(beta0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0_rcpp(mu0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent0_rcpp(gamma_dependent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_independent0_rcpp(gamma_independent0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs0_rcpp(transition_probs0_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist0_rcpp(initial_dist0_rcppSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_min(transition_probs_minSEXP);
    Rcpp::traits::input_parameter< double >::type transition_probs_max(transition_probs_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min(sigma_minSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(EMcppARMSMH(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// LikelihoodMSIAR
SEXP LikelihoodMSIAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp, Rcpp::NumericVector sigma0_rcpp, double penalty_term);
RcppExport SEXP _rMSWITCH_LikelihoodMSIAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP penalty_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_rcpp(initial_dist_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_term(penalty_termSEXP);
    rcpp_result_gen = Rcpp::wrap(LikelihoodMSIAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, sigma0_rcpp, penalty_term));
    return rcpp_result_gen;
END_RCPP
}
// LikelihoodMSMAR
SEXP LikelihoodMSMAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_extended_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_LikelihoodMSMAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_extended_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_extended_rcpp(initial_dist_extended_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(LikelihoodMSMAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// LikelihoodsMSIAR
SEXP LikelihoodsMSIAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp, Rcpp::NumericVector sigma0_rcpp, double penalty_term);
RcppExport SEXP _rMSWITCH_LikelihoodsMSIAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP, SEXP sigma0_rcppSEXP, SEXP penalty_termSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_rcpp(initial_dist_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma0_rcpp(sigma0_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_term(penalty_termSEXP);
    rcpp_result_gen = Rcpp::wrap(LikelihoodsMSIAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, sigma0_rcpp, penalty_term));
    return rcpp_result_gen;
END_RCPP
}
// LikelihoodsMSMAR
SEXP LikelihoodsMSMAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_extended_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_LikelihoodsMSMAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_extended_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_extended_rcpp(initial_dist_extended_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(LikelihoodsMSMAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// PosteriorProbsMSIAR
SEXP PosteriorProbsMSIAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp);
RcppExport SEXP _rMSWITCH_PosteriorProbsMSIAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_rcpp(initial_dist_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(PosteriorProbsMSIAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp));
    return rcpp_result_gen;
END_RCPP
}
// PosteriorProbsMSMAR
SEXP PosteriorProbsMSMAR(Rcpp::NumericVector y_rcpp, Rcpp::NumericMatrix y_lagged_rcpp, Rcpp::NumericMatrix z_dependent_rcpp, Rcpp::NumericMatrix z_independent_rcpp, Rcpp::NumericMatrix z_dependent_lagged_rcpp, Rcpp::NumericMatrix z_independent_lagged_rcpp, Rcpp::NumericMatrix transition_probs_rcpp, Rcpp::NumericVector initial_dist_extended_rcpp, Rcpp::NumericMatrix beta_rcpp, Rcpp::NumericVector mu_rcpp, Rcpp::NumericVector sigma_rcpp, Rcpp::NumericMatrix gamma_dependent_rcpp, Rcpp::NumericVector gamma_independent_rcpp, Rcpp::IntegerMatrix state_conversion_mat_rcpp);
RcppExport SEXP _rMSWITCH_PosteriorProbsMSMAR(SEXP y_rcppSEXP, SEXP y_lagged_rcppSEXP, SEXP z_dependent_rcppSEXP, SEXP z_independent_rcppSEXP, SEXP z_dependent_lagged_rcppSEXP, SEXP z_independent_lagged_rcppSEXP, SEXP transition_probs_rcppSEXP, SEXP initial_dist_extended_rcppSEXP, SEXP beta_rcppSEXP, SEXP mu_rcppSEXP, SEXP sigma_rcppSEXP, SEXP gamma_dependent_rcppSEXP, SEXP gamma_independent_rcppSEXP, SEXP state_conversion_mat_rcppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_rcpp(y_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_lagged_rcpp(y_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_rcpp(z_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_rcpp(z_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_dependent_lagged_rcpp(z_dependent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type z_independent_lagged_rcpp(z_independent_lagged_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type transition_probs_rcpp(transition_probs_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type initial_dist_extended_rcpp(initial_dist_extended_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta_rcpp(beta_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_rcpp(mu_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_rcpp(sigma_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gamma_dependent_rcpp(gamma_dependent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_independent_rcpp(gamma_independent_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type state_conversion_mat_rcpp(state_conversion_mat_rcppSEXP);
    rcpp_result_gen = Rcpp::wrap(PosteriorProbsMSMAR(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rMSWITCH_EMcppARMSI", (DL_FUNC) &_rMSWITCH_EMcppARMSI, 16},
    {"_rMSWITCH_EMcppARMSIA", (DL_FUNC) &_rMSWITCH_EMcppARMSIA, 16},
    {"_rMSWITCH_EMcppARMSIAH", (DL_FUNC) &_rMSWITCH_EMcppARMSIAH, 16},
    {"_rMSWITCH_EMcppARMSIH", (DL_FUNC) &_rMSWITCH_EMcppARMSIH, 16},
    {"_rMSWITCH_EMcppARMSIHPenalized", (DL_FUNC) &_rMSWITCH_EMcppARMSIHPenalized, 18},
    {"_rMSWITCH_EMcppARMSIHQuZhuo", (DL_FUNC) &_rMSWITCH_EMcppARMSIHQuZhuo, 16},
    {"_rMSWITCH_EMcppARMSIQuZhuo", (DL_FUNC) &_rMSWITCH_EMcppARMSIQuZhuo, 16},
    {"_rMSWITCH_EMcppARMSM", (DL_FUNC) &_rMSWITCH_EMcppARMSM, 19},
    {"_rMSWITCH_EMcppARMSMAH", (DL_FUNC) &_rMSWITCH_EMcppARMSMAH, 19},
    {"_rMSWITCH_EMcppARMSMH", (DL_FUNC) &_rMSWITCH_EMcppARMSMH, 19},
    {"_rMSWITCH_LikelihoodMSIAR", (DL_FUNC) &_rMSWITCH_LikelihoodMSIAR, 13},
    {"_rMSWITCH_LikelihoodMSMAR", (DL_FUNC) &_rMSWITCH_LikelihoodMSMAR, 14},
    {"_rMSWITCH_LikelihoodsMSIAR", (DL_FUNC) &_rMSWITCH_LikelihoodsMSIAR, 13},
    {"_rMSWITCH_LikelihoodsMSMAR", (DL_FUNC) &_rMSWITCH_LikelihoodsMSMAR, 14},
    {"_rMSWITCH_PosteriorProbsMSIAR", (DL_FUNC) &_rMSWITCH_PosteriorProbsMSIAR, 11},
    {"_rMSWITCH_PosteriorProbsMSMAR", (DL_FUNC) &_rMSWITCH_PosteriorProbsMSMAR, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_rMSWITCH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
